name: auto-update download url in Formula/p/pputil.rb

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
    - name: echoe tarball url
      run: echo "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
    - run: curl -v -o pputil.source.tar.gz --fail-with-body -sL "${{ github.server_url }}/${{ github.owner }}/pputil/archive/refs/tags/v1.1.13.tar.gz"
    - run: curl -o pputil.source.tar.gz --fail-with-body -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/tags/${{ github.ref_name }}.tar.gz"
    - run: ls -lh
    - name: sha256sum
      run: sha256sum pputil.source.tar.gz | cut -d " " -f 1
    - name: get latest pputil release
      uses: actions/github-script@v7.0.1
      with:
        script: |
          let response = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
            owner: context.repo.owner,
            repo: 'pputil',
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          })
          let release = response.data
          console.log("found release: {release.tag_name}")
          
          console.log('---------------------------------------')
          console.log(release)
          console.log('---------------------------------------')
          

          let source_tar_gz_url = release.tarbal_url
          
          // todo: get sha256 of source
          
        # The GitHub token used to create an authenticated client
        #github-token: # optional, default is ${{ github.token }}
        # Whether to tell the GitHub client to log details of its requests. true or false. Default is to run in debug mode when the GitHub Actions step debug logging is turned on.
        debug: true # optional, default is ${{ runner.debug == '1' }}
        # An optional user-agent string
        #user-agent: # optional, default is actions/github-script
        # A comma-separated list of GraphQL API previews to accept
        #previews: # optional
        # Either "string" or "json" (default "json")—how the result will be encoded
        #result-encoding: # optional, default is json
        # The number of times to retry a request
        #retries: # optional, default is 0
        # A comma separated list of status codes that will NOT be retried e.g. "400,500". No effect unless `retries` is set
        #retry-exempt-status-codes: # optional, default is 400401403404422
        # An optional GitHub REST API URL to connect to a different GitHub instance. For example, https://my.github-enterprise-server.com/api/v3
        #base-url: # optional
